export const contentConstants = {
    GET_INTRODUCTION: 'GET_INTRODUCTION',
    SUCCESS_INTRODUCTION: 'SUCCESS_INTRODUCTION',
    FAILURE_INTRODUCTION: 'FAILURE_INTRODUCTION',

    NEARBY: 'NEARBY',
    RATING_REVIEW: 'RATING_REVIEW',
};